kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      target: PROD
      repo: ktruckenmiller/ssm-get-parameter
      username:
        from_secret: username
      password:
        from_secret: password
      when:
        branch: [master]
        event: [push]


  # - name: upload
  #   image: plugins/s3
  #   settings:
  #     bucket: kloudcover-tools
  #     acl: public-read
  #     source: ssm_get_parameter
  #     target: /tools
